language: ruby

rvm:
  - 2.2.0
  - 2.2.4
  - 2.3.0

sudo: true

script:
  - bundle exec rspec .
  - node_modules/.bin/karma start karma.conf.js --single-run

before_script:
  - npm install

notifications:
  email:
    recipients:
      - trlearning@mail.ru
      - betterhelper@mail.ru
    on_success: always
    on_failure: always

addons:
  code_climate:
    repo_token: 852797c6bce074324df93728c02e994536778162d03dedfc761f6a3b98abdff3